name: Deploy Static Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your desired AWS region

      - name: Deploy Website Beta
        run: |
          aws s3 cp index.html s3://my-resume-2025/ --acl public-read
          aws s3 cp generic.html s3://my-resume-2025/ --acl public-read
          aws s3 cp elements.html s3://my-resume-2025/ --acl public-read
          aws s3 cp images s3://my-resume-2025/images --recursive --acl public-read
          aws s3 cp assets s3://my-resume-2025/assets --recursive --acl public-read


